import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await b.newPage({ viewport: { width: 1400, height: 900 } });
const msgs = [];
p.on("console", (m) => msgs.push(`[${m.type()}] ${m.text()}`));
p.on("pageerror", (e) => msgs.push(`[pageerror] ${e.message}`));
p.on("requestfailed", (r) => msgs.push(`[404?] ${r.url()}`));
p.on("response", (r) => { if (r.status() >= 400) msgs.push(`[${r.status()}] ${r.url()}`); });
await p.goto(process.argv[2], { waitUntil: "networkidle", timeout: 60000 });
await p.waitForTimeout(1200);
console.log(msgs.join("\n").slice(0, 4000));
await b.close();
