import { chromium } from "playwright";
const [,, url, out, w = 1560, h = 1100, full = "1"] = process.argv;
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await b.newPage({ viewport: { width: +w, height: +h }, deviceScaleFactor: 2 });
const errs = [];
p.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
p.on("pageerror", (e) => errs.push(String(e)));
await p.goto(url, { waitUntil: "networkidle", timeout: 60000 });
await p.waitForTimeout(700);
await p.screenshot({ path: out, fullPage: full === "1" });
if (errs.length) console.log("CONSOLE ERRORS:\n" + errs.slice(0, 8).join("\n"));
else console.log("sem erros de console");
await b.close();
